version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/function"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "samsoir"
    assignees:
      - "samsoir"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "samsoir"
    assignees:
      - "samsoir"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Terraform
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "samsoir"
    assignees:
      - "samsoir"
    commit-message:
      prefix: "terraform"
      include: "scope"